[package]
name = "codec5"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
base64-url = "3.0.0"
fpe = "0.6.1"
once_cell = "1.21.3"
rand = "0.9.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
